### PR TITLE
Adding delta test to QC

### PR DESCRIPTION
**Pull request by kenkehoe**
Updated other code to be more better including ensure the attributes set for limits are correct type. Added more tests to test_qc.py to ensure attributes are correctly set. I think I fixed a possible issue with missing value test and higher dimention data.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I don't understand the logs. Is it a failure with the test or flake?

**Comment by AdamTheisen** [comment]
That's strange...  It's showing an error from the aeri code.

+eval 'flake8 --max-line-length=115 --ignore=F401,E402,W504,W605 '
++flake8 --max-line-length=115 --ignore=F401,E402,W504,W605
./act/retrievals/aeri.py:72:15: F541 f-string is missing placeholders

**Comment by AdamTheisen** [comment]
I'll have to look into this a little more

**Comment by AdamTheisen** [comment]
Changing a print statement that I think was causing the issue to raise an error instead.  We'll see if that works.

**Comment by AdamTheisen** [comment]
Looks to be passing unit tests and looks like some good additions.  Will merge in.

**Pull request merged**
