### PR TITLE
Wrapper for reading NOAA data from ASCII

### PR DESCRIPTION
**Pull request by kenkehoe**
This update has a new file with some functions to read the NOAA GML data using the existing ASCII reader. It will correctly read the data, add attributes, convert missing_value, and general awesomeness.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe as a heads up, I am going to pull the test script into the test_io.py file for consistency.  Let me know if you have any objections.

**Comment by kenkehoe** [comment]
OK sounds good.

**Review by jhemedin — APPROVED** [review]
All looks good to me. Approving.

**Review by zssherman — COMMENTED** [review]
Everything looks good, but had a question, is there a difference between xarray.drop variable and xarray.__del_item? @AdamTheisen @kenkehoe I'm not familiar, but should we avoid using private functions?

**Comment by AdamTheisen** [comment]
@zssherman interesting catch.  @kenkehoe would you have issues moving to use drop?

**Comment by kenkehoe** [comment]
I have no issue with changing this.

**Comment by kenkehoe** [comment]
I was trying to merge current master with this PR. I hope I didn't break anything.

**Comment by kenkehoe** [comment]
Sorry, looks  like I broke it. I may have another update so we'll see if that try passes. I'm assuming something is getting hung up and this error is just timing out?

**Comment by AdamTheisen** [comment]
@kenkehoe  I restarted the run.  The 3.7 version has been hanging up recently

**Comment by AdamTheisen** [comment]
@kenkehoe thank you for all the work on this, things are looking good.  Going to merge in!

**Pull request merged**
