### PR TITLE
TST: Addition of contour tests

### PR DESCRIPTION
**Pull request by zssherman**
@AdamTheisen This is what I mentioned before with a parameter for contour, not sure if this is this route to go, however.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@zssherman  this looks good!  I would probably default it to do the filled contours though initially.  That's my only feedback.

Also, not sure what this error is from since you didn't do anything with the QC

FAILED act/tests/test_qc.py::test_arm_qc - IndexError: list index out of range

**Comment by zssherman** [comment]
Yeah I wasn't too sure of that as well not sure why its failing. And sounds good, i'll change the default

**Comment by AdamTheisen** [comment]
@zssherman it looks like the DQR webservice is down...  Checking on it now

**Comment by AdamTheisen** [comment]
@zssherman everything is passing now and this looks good.  I will go ahead with the merge.  Thanks!

**Pull request merged**
