### PR TITLE
Add Google Analytics ID

### PR DESCRIPTION
**Pull request by mgrover1**
Add a Google Analytics ID to the `conf.py` file used by sphinx. For those interested in having access the analytics, you will need to send over your gmail address

Fixes #396

### CODE REVIEW

**Comment by mgrover1** [comment]
@zssherman do you have time this afternoon to take a quick look at this review?

**Comment by AdamTheisen** [comment]
@mgrover1  you can check it out here: [Coveralls](https://coveralls.io/builds/46749022)

The biggest decreases are the cropscape and armfiles for the webservices which are [run on merge with the tests](https://coveralls.io/builds/46749022).

**Comment by AdamTheisen** [comment]
Going to swap out reviewer approval btu @zssherman always welcome to review this as well when you can.

**Review by AdamTheisen — APPROVED** [review]

**Comment by zssherman** [comment]
Looks good to me!

**Comment by zssherman** [comment]
@mgrover1 How is the id generated for the analytics out of curiosity? Yeah this would be a great addition to Py-ART as well.

**Pull request merged**
