### PR TITLE
Phase 1 of Switch from Astral to Skyfield

### PR DESCRIPTION
**Pull request by kenkehoe**
I've refactored the code to use a new function to get solar sunrise, sunset, noon times instead of calling Astral directly. The new function uses skyfield library. The library uses vector processing so is much faster for some ACT operations. The next question is do we add additional libraries in the solar function to allow calling different libraries. I don't know if that is important right now. I did see both performance and accuracy updates with switching to skyfield. This is part of issue #274.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe I'm seeing some interesting errors popping up.  Does skyfield need to download some data first or use a URL to update?

E           OSError: cannot download ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp because <urlopen error ftp error: TimeoutError(110, 'Connection timed out')>
../../../miniconda3/envs/testenv/lib/python3.7/site-packages/skyfield/iokit.py:515: OSError

**Comment by AdamTheisen** [comment]
@zssherman @jhemedin I might need your help on this one.  It looks like the skyfield library needs to download a file from an ftp site but ftp does not seem to be supported on Travis-Ci
https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

Have you ever encountered this before?  We might want to discuss on the skyfield issues board if they can make an option

**Comment by zssherman** [comment]
@AdamTheisen @kenkehoe I have never encounter this before, but I wonder if there is a way or option in skyfield to download via https instead of ftp which will work with travis, its whether or not skyfield provides this.

**Comment by zssherman** [comment]
I'm seeing that this possibly was fix in skyfield 1.31, which is not on condaforge, so many trying skyfield under pip in the ci environment ymls and see if that fixes the issue.

**Comment by zssherman** [comment]
Wait nvm ignore my last point the recent skyfield should be on condaforge the outdated verzion buttons on the condaforge page threw me off.

**Comment by zssherman** [comment]
@kenkehoe @AdamTheisen Can try for load('de421.bsp'), do load.open(https://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp') instead load.open(ftps://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp') There is an option to change the url, I believe open is an attribute to the loader.

**Comment by zssherman** [comment]
I tried both neither, are working, still trying solutions

**Comment by kenkehoe** [comment]
I've found a way to point to the file locally. I think putting the file in the repo will be best as that will not require users to download the file.

**Comment by zssherman** [comment]
@kenkehoe Great! and for testing purposes and with travis stating they don't plan on addressing the ftp issue I think it is the best bet, the file is 12 MB so should be too big of an issue.

**Comment by AdamTheisen** [comment]
@kenkehoe @zssherman Would it be best to try and get the up to date version from the FTP  and if that fails, then go to the local one?  Would it make sense to create a conf directory under the utils area or add this in the test/data area?

**Comment by AdamTheisen** [comment]
Just so we have it, we can get the file through an https here: https://naif.jpl.nasa.gov/pub/naif/JUNO/kernels/spk/de421.bsp

**Comment by AdamTheisen** [comment]
This looks good to me now.  I would like for us to work on fully removing astral before we do another release of the code.  I'll try and make that a priority over the next week

**Review by zssherman — APPROVED** [review]
Looks good to me @AdamTheisen @kenkehoe and I agree removing Astral before the next release would be a good idea.

**Comment by kenkehoe** [comment]
@cgodine do you know if we are calling the older Astral functions? I didn't remove that old functions.

**Comment by cgodine** [comment]
@kenkehoe i believe right now there are calls to each major version of astral (1.x and 2.x), where if 2.x is not installed it will use the older version method calls.

**Comment by AdamTheisen** [comment]
@kenkehoe @cgodine I'll take a look at what's left to sort through and track in #274 .  Sound good?

**Comment by kenkehoe** [comment]
@AdamTheisen OK. I think the only place Astral is still called is add_solar_variable() and the test scripts.

**Pull request merged**
