### PR TITLE
ENH: Adding to unit tests and fixed one bug with the sog/cog code

### PR DESCRIPTION
**Pull request by AdamTheisen**
Updating the utils unit tests to hopefully increase the code coverage

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen The tests themselves look fine to me, the error seems to be a coveralls url change. I followed the link and its broken. Does the coveralls link get changed on our end somewhere?

**Comment by AdamTheisen** [comment]
That is weird, it was showing everything passed yesterday. I'll check it out

**Comment by AdamTheisen** [comment]
@zssherman I'm somewhat at a loss here.  The only fix I could find was adding in a COVERALLS_REPO_TOKEN environment variable in travis-ci with the coveralls token but that did not actually fix it.  Could this be a travis-ci/coveralls issue on the backend?

**Comment by zssherman** [comment]
I'm honestly not sure, I'm not familiar with coveralls. Wonder if their page was just down yesterday. And rerunning can see if it that fixes it. If not ill have to read up on it.

**Comment by zssherman** [comment]
Its possible it can be on the backend at the moment. I don't see any current related issues on coveralls github. Where does the token come from thats in the travis yml file?

**Comment by AdamTheisen** [comment]
There's not a token in the travis yml file.  I set the coveralls token up as an environment variable on the travis-ci page/settings.  Interestingly, I triggered a build through the travis-ci page (not through the PR) and it built fine

**Comment by AdamTheisen** [comment]
Closing this out and referring to #267

**Pull request closed without merging**
