### PR TITLE
Coveralls update

### PR DESCRIPTION
**Pull request by kenkehoe**
Made more tests to get higher percentage for testing with coveralls. Actually found two issues so was worth the effort.

### CODE REVIEW

**Comment by kenkehoe** [comment]
PEP8 stuff. Working on it.

**Comment by AdamTheisen** [comment]
@kenkehoe looks like a good addition.  Only question I have is on the commented out code and what that was for.  Can we remove all that code that's commented out?

**Comment by kenkehoe** [comment]
Oh good catch, that code should not be commented out.

**Comment by AdamTheisen** [comment]
Thanks for the updates @kenkehoe , definitely helps with the code coverage

**Pull request merged**
