### PR TITLE
CI: Pandas remove

### PR DESCRIPTION
**Pull request by zssherman**
Had to reopen PR as PR wasn't updating to new commits (First for everything). Also add timeout for get_ord stalling

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen @mgrover1 Thoughts on adding a pytest-timeout module to pass on the get_ord tests if it goes longer then 5 minutes? This happens every PR for atleast one of the suites

**Comment by mgrover1** [comment]
> @AdamTheisen @mgrover1 Thoughts on adding a pytest-timeout module to pass on the get_ord tests if it goes longer then 5 minutes? This happens every PR for atleast one of the suites. Granted I don't know why the io_write stalls for some tests sometimes

I think this brings up a bigger issue here - we should add sample files to test on and not rely on hitting these servers since a suite of python versions + machines will often overload their bandwidth. I would rather have a single file we test against that we know is on a system with improved bandwidth than pass when things timeout

**Comment by AdamTheisen** [comment]
@mgrover1 @zssherman I thought we added a timeout to that test already but maybe not. I think we should discuss the file part more.  We've had cases in the past where the API updated and it was only through these tests that we would find it. If we are going off a static file we could be using outdated formats. Thoughts?

**Comment by zssherman** [comment]
@AdamTheisen @mgrover1 Yeah I agree on testing the API so we know if something changes. However I also agree with bandwidth issues as well, is there a way to ping the API and not download the file to just see if the path is valid? Also we did not have the timeout, also I believed it was suppose to skip it if it took to long from the documentation, but it looks like it failed the testing suite which isn't what I wanted... so the timeout might not work anyways

**Comment by zssherman** [comment]
@AdamTheisen I removed the pytest timeout stuff, are we good to merge this? This will fix the CI for some of the other PRs I have

**Review by mgrover1 — APPROVED** [review]

**Review by AdamTheisen — APPROVED** [review]
@zssherman please go ahead!

**Pull request merged**
