### PR TITLE
Units

### PR DESCRIPTION
**Pull request by kenkehoe**
This PR is to implement #253 . This will be a nicer way to change the units in the dataset than manually changing them. This will allow changing all variables with a loop that are compatible with the request unit or a select set of variables.

I'm having an issue with a different function test failing now that was fine before. Going to make this PR to see if TravisCI has the same failure.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I don't have much for unit conversion examples. Do you think we should add that?

**Comment by AdamTheisen** [comment]
@kenkehoe Examples would be good, but I don't think it is necessary as part of this PR.

@jhemedin @zssherman would either of you have time to take a look at this new class and give it a run through.

**Comment by kenkehoe** [comment]
I've added an example since it's not obvious the method exists.

**Comment by AdamTheisen** [comment]
@kenkehoe got a chance to look at this and the main question i have is does this need to be a Class?  Does that do anything for us @zssherman ??

**Comment by kenkehoe** [comment]
I wanted to make this a method so the function does not need to be imported. We could put in a different class name, but I thought the name was generic enough to add more in the future.

**Comment by zssherman** [comment]
@AdamTheisen I'm not too familiar yet with accessors, but it almost looks its a class so that when you read a file, the object can just called change units instead of calling change units and imputing the obj as a parameter and does the change inplace, but im not sure 100% sure. The function itself looks fine as does the tests and example. But seems other unit tools in ACT are functions, so I think this is more a consistency thing, I'm not sure on which route to take or if this has to be a class.

**Comment by zssherman** [comment]
I commented right when Ken's message loaded for me haha

**Comment by zssherman** [comment]
To simply the code and more on the side of Python standards, a class might be too much for what the code is trying to do, but for the simplicity on users, the class might be simpler and easier access, its more on which we prefer and might have to vote on.

**Comment by zssherman** [comment]
Also if we plan on adding more functions within the scope of the class, then a class would be preferable.

**Comment by AdamTheisen** [comment]
Thanks @zssherman.  @kenkehoe if you expect that we will have more functions to add under this class in the future, then I would say we can leave as is.  Will wait until tomorrow for final comments before merging

**Comment by kenkehoe** [comment]
I think we will add additional utils methods in the future. They will be called under act.utils.* methods. I think we can call the class anything you want without breaking the code since the class name is not called directly.

**Comment by AdamTheisen** [comment]
Given the expectation that we will add more under this in the future, I am fine with merging as is.

**Pull request merged**
