### PR TITLE
Xlim single value warning

### LINKED ISSUE #629: Attempting to set identical low and high xlims
* ACT version: 1.4.0
* Python version: 3.8.13
* Operating System: Linux

### Description
When processing in an automated queue we sometimes process when there are few time steps. The process does not fail but does produce a warning. 

/.conda/envs/dqo-base/lib/python3.8/site-packages/act/plotting/timeseriesdisplay.py:214: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.

I want to add a check when setting xlim values to ensure start and end are not the same. If so automatically expand the xlim to exclude the warning.

### PR DESCRIPTION
**Pull request by kenkehoe**
This will check if the xlim is attempting to set a single value for start and end limit of plot. If so will expand by 1 second on either side so there is no warning about setting the limit to a single value.

- [ X] Closes #629 
- [X ] Tests added
- [ X] PEP8 Standards or use of linter
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Review by zssherman — CHANGES_REQUESTED** [review]
The changes looks good to me, the only thing I suggest is backwards compatibility with the colormap change. I would do:

```
    try:
        matplotlib.colormaps.register(name=full_name, cmap=cmap, force=True)
    except AttributeError:
        matplotlib.cm.register_cmap(name=full_name, cmap=cmap)
 ```

**Comment by kenkehoe** [comment]
Windows-3.7 is taking a very long time. Is this to be expected?

**Comment by kenkehoe** [comment]
OK should we restart the testing?

**Comment by zssherman** [comment]
Yep restarting now

**Pull request merged**
