### PR TITLE
ADD: Percent calm to wind rose.

### PR DESCRIPTION
**Pull request by rcjackson**
I have modified the wind rose plotter to add the percent of time the wind is calm in the center of the graph, related to issue #305.
test_wind_rose

### CODE REVIEW

**Comment by rcjackson** [comment]
Right now calm is 1 m/s, perhaps I can make this one user adjustable?

**Comment by AdamTheisen** [comment]
Restarting tests as one was failing in the discovery module which is unrelated to this PR

**Comment by AdamTheisen** [comment]
Note, we determined that the ASOS data changes were due to a bug fix on their end.  The script for returning the data was not handling the hour specification properly.  Verified that the current values are correct.

**Comment by AdamTheisen** [comment]
Assigning to @jhemedin to review and merge

**Review by jhemedin — APPROVED** [review]
updates look good to me. Accepting and merging.

**Pull request merged**
