### PR TITLE
Adding generic writer to clean up Dataset before writing to file with .to_netcdf()

### PR DESCRIPTION
**Pull request by kenkehoe**
Because we add some global attributes to the Dataset when reading, and modify the QC attributes, we need to fix some of it before writing to be CF compliant. This will fix some of the attributes to be character arrays instead of string arrays. Resolves Issue #210 .

### CODE REVIEW

**Comment by kenkehoe** [comment]
Looks like an error in code I did not change. Could this be a change in a cartopy version or library used by cartopy?

**Comment by AdamTheisen** [comment]
@kenkehoe Good timing!  I started working on this yesterday.  Yes, there was an issue that came up in the release of act-atmos on anaconda that was related to metpy and ultimately cartopy.  I got it fixed for the anaconda release by limiting the version used for building (whole different process) but am running into core dumps when I try and fix it in ACT itself.  

It's been one hoop after another, but hopefully I can get it resolved in the next day or two.

**Comment by AdamTheisen** [comment]
@kenkehoe @rcjackson @zssherman   I will push my changes tonight or tomorrow but I have most of the issues ironed out except for a core dump on Travis-CI related to the test_geoplot script.  I've not been able to sort it out, but it passes when I comment that test out.  I'm going to keep testing tonight, but I might just leave it commented out for now.

**Comment by kenkehoe** [comment]
@AdamTheisen OK sounds good. There are a lot of libraries used by the time the geoplot script is run so that is not all that surprising. I'm OK with commenting it out.

**Comment by kenkehoe** [comment]
OK I've implemented tempfile to handle the temporary directory. Pretty cool little library. Thanks for the heads up @zssherman .

**Comment by AdamTheisen** [comment]
Perfect!  Thanks @kenkehoe!  I've ran into this issue a number of times and am happy to have an easy fix for it.

**Pull request merged**
