### PR TITLE
ENH: Adding cmweather while updating the codebase for support.

### LINKED ISSUE #705: Replace current CVD colormaps with CMWeather
CMWeather was just released through conda so we should look at incorporating into ACT. https://github.com/conda-forge/cmweather-feedstock

### PR DESCRIPTION
**Pull request by zssherman**
- [x] Closes #705
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter

### CODE REVIEW

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Looks like there a few linting errors

**Comment by zssherman** [comment]
@mgrover1 Yep, fixing now!

**Comment by zssherman** [comment]
Confused on why the git comparison is showing i changed a whole entire file...

**Comment by zssherman** [comment]
Let me check something

**Review by mgrover1 — APPROVED** [review]
This looks great - nice work @zssherman

**Comment by zssherman** [comment]
@AdamTheisen I don't think this should have any impact on systems until there is a release, then ARM systems will need to have cmweather installed, but this should be good to go for now if your cool with me merging?

**Comment by mgrover1** [comment]
When they go to update ACT, it will have it as a new dependency which should solve the issue - the update should go hand in hand

**Comment by zssherman** [comment]
@mgrover1 Good point! I was thinking if they install the repo etc outside of conda-forge, but you made me realized the requirements etc should handle that haha.

**Comment by mgrover1** [comment]
Yes! This is where dependencies + versioning come in clutch. I think we can go ahead and merge?

**Comment by zssherman** [comment]
@mgrover1 merging!

**Pull request merged**
