### PR TITLE
FIX: A fix for 'methods' error.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
Actually if it was methods, it should be _init__ now

**Comment by zssherman** [comment]
Hmm can't figure out the error...

**Comment by AdamTheisen** [comment]
@zssherman I've tried a number of things on my own fork, but can't seem to get anything to work.  Do you have any leads on what may be causing this?

**Comment by AdamTheisen** [comment]
I'm actually seeing failures with the unit tests now on my local system after trying to update my environment to what is running on travis.  Errors with numpy indicating it doesn't have a '__version__'.  Maybe something else is going on with the build environment?

**Comment by zssherman** [comment]
I haven't run into the numpy error, thats interesting. Can you post the full error message your seeing?

**Comment by AdamTheisen** [comment]
@zssherman I ended up doing a complete reinstall of my environment and it fixed it.  It was when I was trying to install numpy 1.18.5 to match what I was seeing on travis-ci.

**Comment by AdamTheisen** [comment]
@zssherman I think I got it working on my fork.  Will try and push the updates to your branch

**Comment by AdamTheisen** [comment]
Travis and coveralls passing now.  Will merge.

**Pull request merged**
