### PR TITLE
Skewt

### LINKED ISSUE #607: Make SkewT Display More Flexible with Matplotlib
While taking a look at #606 , I noticed that there is not currently a way to feed in a user-defined figure or axes to the SkewT Display. This would be an important feature to add, enabling users to customize their plots more, and interact with other displays.

### PR DESCRIPTION
**Pull request by AdamTheisen**
- [x] Closes #607 and #606 
- [x] Tests added
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by mgrover1** [comment]
@AdamTheisen it does appear these are remaining SkewT plots... the temperature/pressure lines should be skewed with decreasing pressure.

Can you check to make sure the axes are set to be skewed?

Here is what the test plot looks like:

Screenshot 2023-03-20 at 8 16 05 AM

And what it should it look like (not the same sounding, but notice the temperature/pressure lines)
image

**Comment by mgrover1** [comment]
I think the key here is making sure the axis type is still `SkewXAxes` and `SkewYAxes`

https://github.com/Unidata/MetPy/blob/main/src/metpy/plots/skewt.py#L162

**Comment by AdamTheisen** [comment]
@mgrover1 @zssherman I have a fix but it would require matplotlib >= 3.7 for this plot.  Is this acceptable?

**Comment by AdamTheisen** [comment]
I can't seem to see the updated baseline plots on here but these are it
test_enhanced_skewt_plot

test_enhanced_skewt_plot_2

**Comment by zssherman** [comment]
@AdamTheisen Pinning matplotlib I think would be fine if it works with all the CI python versions

**Comment by AdamTheisen** [comment]
@zssherman okay, I'll update the requirements files when I get a chance.  The error right now looks like what I was getting when I didn't have matplotlib 3.7

**Comment by mgrover1** [comment]
Yeah, metpy does not support Python 3.7, so there will not be any fixes for that error

**Comment by AdamTheisen** [comment]
@mgrover1 @zssherman  looks like the latest error is saying matplotlib is not valid for 3.7.  Would we want to drop 3.7 testing?

**Comment by mgrover1** [comment]
Yeah, and I think we want >=3.8 since 3.7 isn't supported

**Review by mgrover1 — APPROVED** [review]

**Comment by mgrover1** [comment]
Tests are passing! Thanks for putting this together @AdamTheisen

**Comment by AdamTheisen** [comment]
Nothing else is planned at this time!  Will merge in

**Pull request merged**
