### PR TITLE
ADD: Adding code to convert data to AmeriFlux variable naming convent…

### PR DESCRIPTION
**Pull request by AdamTheisen**
…ions.

- [x] Tests added
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]
Nice work @AdamTheisen

**Review by zssherman — APPROVED** [review]
Looks good to me as well!

**Comment by zssherman** [comment]
@AdamTheisen We good to merge this in? I probably do a release to get all these changes in.

**Comment by AdamTheisen** [comment]
@zssherman sorry, yes please go ahead!

**Pull request merged**
