### PR TITLE
ADD: Adding example for bringing BNF data sources together for plotting

### PR DESCRIPTION
**Pull request by AdamTheisen**
- [ ] Tests added
- [ ] Documentation reflects changes
- [ ] PEP8 Standards or use of linter
- [ ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
@AdamTheisen Looks like the doc build for the new example is failing.

**Comment by zssherman** [comment]
@AdamTheisen Looks like its the download arm data url for the new example not working.

**Comment by AdamTheisen** [comment]
I had a feeling!  I'll have to update my handling when the environment variables are not available.

**Comment by zssherman** [comment]
@AdamTheisen Feel free to merge if this is all good now.

**Pull request merged**
