### PR TITLE
ADD: Adding antivirus scanning

### PR DESCRIPTION
**Pull request by AdamTheisen**

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen Looks good to me! Is the line:
uses: djdefi/gitavscan@main

universal? Can I do this as a PR with Py-ART?

**Review by zssherman — APPROVED** [review]

**Comment by AdamTheisen** [comment]
@zssherman The action can be found here so it is universal https://github.com/marketplace/actions/git-anti-virus-scan

**Comment by zssherman** [comment]
Cool thank you!

**Comment by zssherman** [comment]
Rerunning tests due to stalled windows test

**Pull request merged**
