### PR TITLE
FIX: Many warning fixes for ACT.

### PR DESCRIPTION
**Pull request by zssherman**
These fixes include datetime utc changes, missing images, xarray.dims to sizes changes and more.

Note I did a PR for icartt as well to fix there warnings, which will then suppress ours and will be doing one for PySP2 as well.

- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter

### CODE REVIEW

**Comment by zssherman** [comment]
For more on timezone fun, see here:
https://github.com/Unidata/MetPy/issues/3298

**Review by AdamTheisen — COMMENTED** [review]
@zssherman  are those barb baseline plots what we're producing now?  Seems like there's not a lot there... No actual barbs.  Thoughts?

**Comment by zssherman** [comment]
@AdamTheisen Originally the plots u_v 3, 4 and5 were not producing plots and had a warning of future errors because of it, so I added the plot comparison plot. In terms of the small amounts of data in them, compared to u_v_1 I'm seeing the use of a real dataset, were the rest use a small fake ds, which could be the reason for that? Also the bins are set low it looks like. So i'm not 100% if because they are test ds that there is barely any data because its np.linspace fake data? But that was my assumption when I saw the plots.

**Comment by zssherman** [comment]
@AdamTheisen Sounds good!

**Pull request merged**
