### PR TITLE
Adding filename parsing for ARM filenames.

### PR DESCRIPTION
**Pull request by kenkehoe**
- [ X] Closes #700 
- [ X] Tests added
- [ X] Documentation reflects changes
- [ X] PEP8 Standards or use of linter

### CODE REVIEW

**Comment by kenkehoe** [comment]
I'm assuming this just timed out and the tests were OK. Can you rerun the testing?

**Comment by mgrover1** [comment]
rerunning now @kenkehoe !

**Review by mgrover1 — APPROVED** [review]
This looks great - tests pass, and the code here looks solid! Thanks for adding the tests/example here too @kenkehoe

**Comment by AdamTheisen** [comment]
Agreed @mgrover1 !  Thanks for getting this in @kenkehoe, very much appreciated!  We can close out #700 once this is merged.

**Review by AdamTheisen — APPROVED** [review]

**Pull request merged**
