### PR TITLE
ENH: Bug fix for geoplot example

### PR DESCRIPTION
**Pull request by AdamTheisen**
There's an issue with the cartopy Stamen that is causing errors.  While we sort through that, setting the stamen to terrain and the tile to 9 seems to produce consistent results.

### CODE REVIEW

**Comment by zssherman** [comment]
Thanks @AdamTheisen for the fix!

**Comment by zssherman** [comment]
Looks like the error is a syntax error

**Review by mgrover1 — APPROVED** [review]
Great!!

**Comment by AdamTheisen** [comment]
It looks like one test failed so maybe this is not a permanent solution.  Rerunning to see what it does.

**Comment by AdamTheisen** [comment]
@zssherman @mgrover1 there was one last error with the geoplot test.  I'm wondering if I should update the geoplot test to follow the example.  Thoughts?

**Pull request merged**
