### PR TITLE
ADD: New example showing how to use ACT to work with ARM and Satellit…

### PR DESCRIPTION
**Pull request by AdamTheisen**
…e data

- [ ] Documentation reflects changes
- [ ] PEP8 Standards or use of linter
- [ ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Note, this won't fully pass until the PR for arm-test-data is merged.

**Comment by AdamTheisen** [comment]
image (13)
image (12)

**Comment by zssherman** [comment]
Error seems to be some sort of key error ir_temperature

**Comment by zssherman** [comment]
I'm putting in a fix now.

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
Things look good, merging.

**Pull request merged**
