### PR TITLE
ARM AAF Flight Track - GeographicPlotDisplay Example

### PR DESCRIPTION
**Pull request by jrobrien91**
Example on plotting the ARM AAF flight track, utilizing the read_icartt and geographicplotdisplay functions.

Additionally, some clean up of the geodisplay links

### CODE REVIEW

**Comment by zssherman** [comment]
@jrobrien91 Thanks for the PR! Looks like pylint stuff that needs fixing.

**Comment by jrobrien91** [comment]
@zssherman added the pylint corrections! thanks for pointing that out

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
@jrobrien91 the only other thing I was debating was whether to rename the plot file to be more specific, so instead of plot_geographic.py, plot_arm_aaf_track or something

**Comment by jrobrien91** [comment]
plot_aaf_track? @zssherman

**Comment by zssherman** [comment]
@jrobrien91 Yeah that would work!

**Comment by jrobrien91** [comment]
@zssherman let me know if there is anything else I need to do here!

**Comment by zssherman** [comment]
Nope looks @jrobrien91! Merging

**Pull request merged**
