### PR TITLE
Fixing issues when adding DQRs to ACT object

### PR DESCRIPTION
**Pull request by kenkehoe**
This is to fix issue #323 . Turns out it was adding a new test for each time range.

While testing found issue overplotting failing data and using absolute limits.

Since I was in there, decided to reduce warnings by using finally: with plot tests to close plot after used and capture warning with calculation of u & v direction.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@zssherman are there any issues with wrapping the figure returns in the unit tests with a try?

**Comment by kenkehoe** [comment]
I'm looking into a warning that was created by changes to previous PR. Maybe hold off on approval just yet.

**Comment by zssherman** [comment]
@AdamTheisen I don't think so, It should be fine

**Comment by kenkehoe** [comment]
OK, after looking into this I think read_netcdf() is correct and our production system is just behind on current updates in GitHub. If this is good to merge I say go ahead.

Can we also then make a conda-forge release for 1.0.3 to resolve the issues on our production system?

**Comment by AdamTheisen** [comment]
@kenkehoe once @zssherman approves and merges in, I can work on a new micro release.

**Review by zssherman — APPROVED** [review]

**Pull request merged**
