### PR TITLE
ENH: Updates to the FFT radiometer test to allow users to plot up FFT

### PR DESCRIPTION
**Pull request by AdamTheisen**
Adds the FFT and frequency data to the object so that users can plot up the data like so:

`  
# Set up plot information
    nrows = 6 
    ncols = 4
    x = 0
    y = 0
    fig, ax = plt.subplots(nrows, ncols, figsize=(15,10))
    sdate = pd.to_datetime(obj['time'].values[0])
    # Get upper and lower frequencies to look for shading
    upper = obj['fft'].attrs['upper_freq']
    lower = obj['fft'].attrs['lower_freq']
    #Plots data up in hourly increments
    for i in range(24):
        dummy = obj.sel({'time': slice(sdate.replace(hour=i, minute=0, second=0),
                                       sdate.replace(hour=i, minute=0, second=0) +
                                       pd.Timedelta(1,'hours'))})

        # Shades the background of where to look for spikes
        # Plots FFT if available
        ax[x,y].set_xlim([np.nanmin(obj['fft_freq']), np.nanmax(obj['fft_freq'])])
        ax[x, y].axvspan(lower[0], upper[0], color='red', alpha=0.25)
        ax[x, y].axvspan(lower[1], upper[1], color='red', alpha=0.25)
        ax[x, y].set_title(str(i).zfill(2) + '00')
        if len(dummy['time'].values) > 1:
            ax[x, y].plot(np.transpose(dummy['fft_freq'].values), np.transpose(dummy['fft'].values),
                         'k', linestyle='solid')
        y += 1
        if y == ncols:
            y = 0
            x += 1
    plt.tight_layout()
    plt.show()`

### CODE REVIEW

**Comment by AdamTheisen** [comment]
shading

**Comment by AdamTheisen** [comment]
@kenkehoe @ajsockol @cgodine The above is the code and the resultant plot to help with the shading detection.  Essentially, when you see the 2 peaks in the shaded region is when you have shading problems.  In the case above, it shows up between 1800 and. 21-2200 UTC.  Which corresponds to the flag being generated

shading_qc

**Comment by kenkehoe** [comment]
OK thanks. This will work great. Plots look wonderful.

**Review by zssherman — APPROVED** [review]
@AdamTheisen Only thing I see is a spelling error, floa instead of float for the docs for lat in the doctoring besides that it looks good.

**Comment by AdamTheisen** [comment]
Thanks @zssherman @kenkehoe .  Made the spelling corrections and will merge once tests run again

**Pull request merged**
