### PR TITLE
Updated read_netcdf() function to be more ARM specific

### PR DESCRIPTION
**Pull request by kenkehoe**
The generic netCDF reading function was not able to read some messed up ARM files. These updates make the code more general for messed up ARM files and gives options to user for how to parse and set times in the Dataset. Resolves issue #611 .

### CODE REVIEW

**Comment by zssherman** [comment]
@kenkehoe Thanks for submitting this change, I'll get to reviewing this now. Looks like its failing due to an assertion error in the testing.

**Comment by zssherman** [comment]
@kenkehoe I did some mispelling changes, once the tests pass, will merge.

**Review by zssherman — APPROVED** [review]

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe!  I did a test with this code on a number of cases and works well!  I did run into an issue with the test_qctests_dos that it looks like you tried to fix.  I'm going to rerun the tests and make sure.  If they pass, I'll merge in.

**Comment by AdamTheisen** [comment]
Definitely strange as the persistence test does not seem to work on my system for this test.  If this fails on merge, I narrowed it down on my system to this line.  Also updating all my libraries just in case.

715: data = np.around(data, decimals=3)

**Pull request merged**
