### PR TITLE
Matplotlib Marker keyword

### PR DESCRIPTION
**Pull request by kenkehoe**
The marker keyword is hardcoded into a plotting call, so specifying the marker in an ACT plotting call is causing a conflict. This PR puts the marker in the kwargs dict so we can have a default and can override default. Found a few other instances of keywords being set in the call so fixed those as well.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I don't think the tests ran for this. Can we try them again?

**Comment by zssherman** [comment]
I believe because we are adding the ax.plot for lines, the images do not match for the unit tests and that why its failing.

**Comment by kenkehoe** [comment]
@zssherman  OK I see the issue. I can drop the lines but I'm confused why the colors have changed. Any ideas? I can save an updated image if that is needed.

**Comment by AdamTheisen** [comment]
@kenkehoe I think it might be that your kwargs['edgecolors'] has an s and the keywords were just edgecolor

**Comment by AdamTheisen** [comment]
I'll take a look at this.  Curious why we would need to set linestyle to 'None' on this

display.plot('backscatter', force_line_plot=True, linestyle='None')

**Comment by kenkehoe** [comment]
I think the default is to draw the line for Matplotlib. The baseline image does not have lines. The strange thing I'm seeing is that the colors are different. I wonder if the limit for image comparison is not tight enough since my colors are different than the baseline, but tests on my laptop would pass. Most of the image is just dots so connecting the lines is not obvious with so many points.

**Comment by kenkehoe** [comment]
Now I see there are two different keywords: edgecolor and edgcolors. I may need to double check I managed both correctly.

**Comment by AdamTheisen** [comment]
@kenkehoe I changed to edgecolor and it seems to work without the change to the test_plotting script

**Comment by kenkehoe** [comment]
I think edgecolors was the correct keyword the pcolormesh call. But it also looks like we are setting the keyword to the standard default so maybe we just remove the keyword and let the kwargs handle it?

**Comment by zssherman** [comment]
Yeah if its already the default, is edgecolor used often? Well more is it changed often? If not it would probably be better to leave it to the kwargs

**Comment by kenkehoe** [comment]
@AdamTheisen  you OK with removing the keyword from the function call and expect people to just add it via the kwargs method?

**Comment by AdamTheisen** [comment]
@kenkehoe as long as it doesn't change the default behavior I would be ok with that.

**Comment by kenkehoe** [comment]
OK I think my update of edgecolor in the broken_bahr was not quite right. I've updated to be more like the original but add keyword documentation that was missing.

**Comment by AdamTheisen** [comment]
@kenkehoe @zssherman I might have misunderstood.  Was the intent to sent edgecolors to the plot function through kwargs or still have it as a keyword to the plot function and then pass to plot/pcolormesh in kwargs?

**Comment by kenkehoe** [comment]
I think we are not using the default for edgecolors so to set it in a way where it can be overwritten by a keyword I have the keyword set in the normal way, but passed to pcolormesch through kwargs dictionary.

**Comment by AdamTheisen** [comment]
@kenkehoe  thanks for jogging my memory there.  Will approve and merge unless @zssherman has anything else to address.

**Review by AdamTheisen — APPROVED** [review]

**Pull request merged**
