### PR TITLE
Add AERIoe workflow example

### PR DESCRIPTION
**Pull request by dennyh-ssec**
- [x] Closes #xxxx
- [x] Tests added
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Thanks @dennyh-ssec !  I am going to make some changes and use the ACT tokens we have set up to download data to make sure this runs

**Comment by AdamTheisen** [comment]
@dennyh-ssec is this the correct output? 
image

**Comment by dennyh-ssec** [comment]
Yes, looks correct.

Denny Hackel
***@***.******@***.***>>
Sci Instrmt Integration Eng @ UW Madison Space Science & Engr. Center
Office: 608-263-0226
Cell: 608-770-1485

On Jun 14, 2023, at 2:46 PM, Adam Theisen ***@***.***> wrote:



@dennyh-ssec<https://github.com/dennyh-ssec> is this the correct output?
[image]<https://user-images.githubusercontent.com/13421074/245916358-d4ae4bf5-6ccc-4305-b9ea-8c2e5cc3fd0b.png>

**Review by zssherman — APPROVED** [review]

**Review by mgrover1 — APPROVED** [review]
This looks fantastic!

**Review by AdamTheisen — APPROVED** [review]

**Comment by AdamTheisen** [comment]
Everything is good to go, merging in!

**Pull request merged**
