### PR TITLE
ENH: Updates for plotting

### PR DESCRIPTION
**Pull request by AdamTheisen**
Updated skew-t plots to make it a little more robust and handle cases where data are subsetted from a 2D array.

- [ ] PEP8 Standards or use of linter
- [ ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by AdamTheisen** [comment]
I'll take a look at these errors when I get some time but it probably won't be soon

**Comment by mgrover1** [comment]
I can dig into this today!

**Comment by zssherman** [comment]
@mgrover1 I might have a fix for this, let me check

**Comment by zssherman** [comment]
@mgrover1 I pushed a fix, if the changes pass, let me know if my changes look reasonable

**Review by mgrover1 — APPROVED** [review]

**Comment by mgrover1** [comment]
Looks great - nice work @zssherman and @AdamTheisen !

**Pull request merged**
