### PR TITLE
TST: Added tests and assert to raise coverage. Main focus stability indices in this PR.

### PR DESCRIPTION
**Pull request by zssherman**
Will do other tests in other PR to avoid overwhelming.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@zssherman looks like just the following issue

./act/tests/test_utils.py:17:43: E712 comparison to False should be 'if cond is False:' or 'if not cond:'

**Comment by AdamTheisen** [comment]
Fantastic work @zssherman !  Everything is passing so I will go ahead and merge

**Comment by zssherman** [comment]
Hmm, I'm not sure how coveralls calculates its numbers, but coverage for stability indices went down from the PR, if I'm reading it right, overall coveralls went up 1%, i'll have to double check...

**Comment by zssherman** [comment]
locally i was up to like 84%

**Pull request merged**
