### PR TITLE
FIX: Addresses #361, use virtual temperature instead of temperature.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen So I think I have a working code, unit tests are probably going to change because values will change, however im going to do a pr, and have a review, because the met side of things I want to check with you all, and if it all looks good ill change the unit tests

**Comment by AdamTheisen** [comment]
@zssherman  as expected, it looks like there are some slight differences in the unit test results'

E           Mismatched elements: 5 / 5 (100%)
E           Max absolute difference: 0.36768183
E           Max relative difference: 0.00136254
E            x: array([270.217682, 270.112815, 270.045454, 269.989816, 269.939635])
E            y: array([269.85    , 269.745307, 269.678057, 269.622511, 269.572413])

**Comment by Meteodan** [comment]
All, I found this conversation and the related #361 when trying to get to the bottom of what would be needed to add the virtual temperature correction to MetPy's CAPE calculations. Unfortunately, I don't think the approach you are using here is correct. The problem comes when you are calling MetPy's `surface_based_cape()` function here: https://github.com/ARM-DOE/ACT/pull/362/files#diff-605c6300a0861a7eaad398f848dd5baa1871d6490dcfcd13224c6f6e9c56d0daL196

While definitely the environmental virtual temperature needs to be used in the calculation, what is happening as near as I can tell is that the `surface_based_cape()` function is internally computing the parcel's *uncorrected* temperature profile and using *that* in the CAPE calculation.  To get the correct CAPE with the virtual temperature correction, the parcel's *virtual* temperature profile needs to be computed as well. Another problem is that, since the environmental virtual temp is being passed in in place of the regular temp, then the starting temperature that is being used internally to compute the parcel profile is using the starting virtual temperature instead, while still using the uncorrected dewpoint. This means that the LCL used internally for the CAPE calculation will be wrong (too high) on top of the parcel profile being incorrectly computed.

**Comment by AdamTheisen** [comment]
@Meteodan,  thanks for reaching out and reporting this.  I turned this into an issue (#631) and we will look into it.  Of course we always welcome contributions from others if you have a potential fix in mind!

**Pull request merged**
