### PR TITLE
Fixing message with ValueError

### PR DESCRIPTION
**Pull request by kenkehoe**
The ValueError message indicates the wrong function. This just fixes the printed message.

### CODE REVIEW

**Comment by zssherman** [comment]
Looks good, will merge after tests pass.

**Comment by kenkehoe** [comment]
Hold off. Found one more thing in this function.

**Comment by zssherman** [comment]
sounds good

**Comment by kenkehoe** [comment]
OK should be good now.

**Comment by zssherman** [comment]
Groovy, merging.

**Pull request merged**
