### PR TITLE
ADD: MPL reader.

### PR DESCRIPTION
**Pull request by zssherman**
Adding a new submodule for mpl. Current adding mplv5 sigma reader. Unit tests and docs are included and also update readme for info on optional dependency. Optional dependency lowered lines of code.

### CODE REVIEW

**Comment by zssherman** [comment]
Might possibly need more in mpl.py for standards, submitting this for review, can always add more.

**Comment by zssherman** [comment]
Error seems to be the coveralls error

**Comment by AdamTheisen** [comment]
@zssherman testing things out and am thinking about changing the coordinates to time/range instead of profile/range for ease of use in ACT plotting.  Trying to plot in pyart if PPI or RHI data will be the next test

-    ds = ds.assign_coords({'profile': ds.profile,
-                           'range': ds.range})
+    ds = ds.swap_dims({'profile': 'time'})
 
+    ds = ds.assign_coords({'time': ds.time,
+                           'range': ds.range})

**Comment by zssherman** [comment]
Gotcha, yeah, I can implement those changes real fast and update the PR.

**Comment by zssherman** [comment]
I also notice too that the datastream string is being set by the tmp file name, bug on my part, I'll fix that.

**Comment by zssherman** [comment]
Updated the code for time as coord and fixed the datastream name issue.

**Comment by AdamTheisen** [comment]
I think this is ready to pull in at the moment as the reader is functional.  We will be working on examples and integration with pyart in a different PR.  @zssherman does that sound good?

**Comment by zssherman** [comment]
That sounds good to me @AdamTheisen!

**Comment by AdamTheisen** [comment]
Merging in, the latest updates to use dask did not break the unit tests and seems to perform well for the test data.

**Pull request merged**
