### PR TITLE
FIX: Fixes for the pyart_obj creation.

### PR DESCRIPTION
**Pull request by zssherman**
np.unique was marking 2 sweeps even though there was 1, which was doubling nrays. Also added brackets for lat, lon, alt, as these need to be singular arrays for Py-ART. Also pep8 style fixes etc.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Looks like a test is failing so we will have to look at some more

        with warnings.catch_warnings():
            # division by zero may occur here but is properly addressed below so
            # the warnings can be ignored
            warnings.simplefilter("ignore", RuntimeWarning)
>           lat_rad = np.arcsin(np.cos(c) * np.sin(lat_0_rad) +
                                y * np.sin(c) * np.cos(lat_0_rad) / rho)
E           ValueError: operands could not be broadcast together with shapes (102,1000) (102,)

**Comment by zssherman** [comment]
Restarting test, setuptools PR was accepted, so should work now.

**Comment by AdamTheisen** [comment]
Just a couple PEP8 issues now.

/act/utils/data_utils.py:562:33: E226 missing whitespace around arithmetic operator
./act/utils/data_utils.py:741:27: E127 continuation line over-indented for visual indent
./act/utils/data_utils.py:744:27: E127 continuation line over-indented for visual indent

**Comment by zssherman** [comment]
Gotcha, pushes PEP8 fixes now.

**Comment by AdamTheisen** [comment]
Looks good, will go ahead and merge.

**Pull request merged**
