### PR TITLE
Preparing for discovery module standardization

### PR DESCRIPTION
**Pull request by AdamTheisen**
Added in warnings in the existing discovery functions and added new files for when we standardize to V2.0.0.  This does not need to wait for V2.0.0 as it has both version.  Will open a new PR to update everything for V2.0.0

- [x] PEP8 Standards or use of linter

### CODE REVIEW

**Comment by zssherman** [comment]
Looks good to me! Thanks @AdamTheisen

**Comment by zssherman** [comment]
Going to get the geoplot example PR in first, then will rerun this PR

**Review by mgrover1 — APPROVED** [review]
Looks good to me!

**Comment by AdamTheisen** [comment]
@zssherman are we good to go on this one as well?

**Comment by zssherman** [comment]
Yep! Merging

**Pull request merged**
