### PR TITLE
FFT Test for Shadowband Radiometers

### PR DESCRIPTION
**Pull request by AdamTheisen**
FFT algorithm to find shading issues with shadowband radiometers (ARM MFRSR, RSS, etc).  Tests are based on Alexandrov et al 2007, but was modified to be able to run on a moving window analysis in order to get a point by point analysis.  

Also updated the qc plot to add a space at the beginning of the wording for better readability.  

Figure_1

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe This should be the same test that's run in the DQ Office, just with some different thresholding/averaging.  Seems to work about the same though.

**Comment by kenkehoe** [comment]
Oh very nice. Thanks for adding this. I'll look into converting our code over to this one.

**Comment by AdamTheisen** [comment]
@rcjackson or @zssherman Want to take a look and sign off or not?

**Comment by rcjackson** [comment]
Looks good to me!

**Pull request merged**
