### PR TITLE
CI: Add linting action that uses pre-commit and ruff.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by zssherman** [comment]
I need to find a way for it to ignore removing the imports in the try and except blocks

**Comment by zssherman** [comment]
@mgrover1 Is there a way for precommit to fix the 600 or so long line errors? Or do i have to manually go in and fix all 600.... Or is there another way around it?

**Comment by mgrover1** [comment]
@zssherman - you can fix these files using ruff, which is part of the pre-commit hooks

See https://docs.astral.sh/ruff/tutorial/#getting-started

You can run
```bash
ruff check . --fix
```
 to automatically go in and fix those files

**Comment by zssherman** [comment]
@mgrover1 Hmm sadly it doesn't do anything at all from the act directory.

**Comment by zssherman** [comment]
@mgrover1 I think I figured it out, was missing that addition of ruff to the pyproject.yml

**Review by mgrover1 — APPROVED** [review]

**Pull request merged**
