### PR TITLE
Update to MPL Depol Ratio Calc

### PR DESCRIPTION
**Pull request by AdamTheisen**
Noticed an issue with the depol calc compared to what the mentor provided.  Updating that correction and the tests.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe @ajsockol @cgodine Just want to make sure you are aware of this update.

**Comment by kenkehoe** [comment]
How much of a difference is there with old code?

**Comment by AdamTheisen** [comment]
@kenkehoe  it's really only with the ratio calculation.  In the old code it was (crosspol/copol) * 100.  This is crosspol/(copol + crosspol) * 100

**Comment by kenkehoe** [comment]
OK I think this is fine.

**Pull request merged**
