### PR TITLE
ADD: 'extract_arm_file_info' to harvest info from lists of ARM

### PR DESCRIPTION
**Pull request by isilber**
filenames without loading the files, thereby saving header reading and processing times

- [ ] Documentation reflects changes

### CODE REVIEW

**Comment by zssherman** [comment]
@isilber Thanks for the PR! Would it be possible to add a unit test for the new function?

**Comment by AdamTheisen** [comment]
Just as a note, I do think it would be beneficial to restructure this like how the DQ Office uses regular expressions to extract the corresponding data.  That would enable it to be more robust and work across all ARM cases.  @kenkehoe thoughts?

**Comment by kenkehoe** [comment]
Sounds good to me. Shall I put our filename parser into ACT?

**Comment by AdamTheisen** [comment]
@isilber thanks again for this PR!  We ended up merging in the code in #708 which performed this functionality.  Let us know if you see any issues and we'll hope tp get you in as a contributor/co-author soon!

**Pull request closed without merging**
