### PR TITLE
ENH: Adding date parser to get_armfiles.

### PR DESCRIPTION
**Pull request by zssherman**
@AdamTheisen Is this kinda what you had in mind for #448 ? Any of these formats are accepted and then turned into the proper string for the query. If so I can add unittests as well.

### CODE REVIEW

**Comment by kenkehoe** [comment]
I agree generalizing this date parsing would be fantastic. Could we add the date_parser() function to the datetime_utils.py file and also add a keyword option for setting the returned value. Maybe pass in the expected value to be passed into strftime so we can use it elsewhere. I believe the DQR function expects YYYYmmdd format.

**Comment by zssherman** [comment]
Did some changes and believe added parameters for above mentioned. Let me know if it looks ok or if I understood correctly and I'll add some unittests.

**Comment by AdamTheisen** [comment]
I think that looks good @zssherman

**Comment by zssherman** [comment]
Groovy, I'll add the unitests to this PR later today.

**Comment by mgrover1** [comment]
@zssherman feel free to merge when you think it's ready!

**Comment by kenkehoe** [comment]
For consistency should we also have a datetime_to_datetime64 function to complement datetime64_to_datetime?

**Pull request merged**
