### PR TITLE
ENH: Combining radiosonde related scripts into one general file

### PR DESCRIPTION
**Pull request by AdamTheisen**

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Issue from #325 with matplotlib.  Once that PR is merged, I'll update this PR

**Comment by AdamTheisen** [comment]
@kenkehoe will this cause any issues with the DQ sonde processing?

**Comment by kenkehoe** [comment]
Let me look...

**Comment by kenkehoe** [comment]
I don't think this will cause an issue. If it does we'll fix it. Go ahead and merge.

**Pull request merged**
