### PR TITLE
FIX: Fixes most warnings within ACT.

### PR DESCRIPTION
**Pull request by zssherman**
Fixes most warnings caused by act code itself, other warnings from dependencies themselves aren't fixed here. 
Uses new syntax for pyproj to remove dep warning. Using no labels to remove cartopy dep. Fixes regex warning.

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen Whenever you get a chance no rush. Who else should have do reviews for PRs?

**Comment by AdamTheisen** [comment]
@zssherman will take a look when I can.  We won't have anyone else really until our new hire starts up in February.

**Comment by zssherman** [comment]
@AdamTheisen Gotcha no worries at all!

**Comment by AdamTheisen** [comment]
This was pretty straight forward and looks good.  All checks pass so will merge

**Pull request merged**
