### PR TITLE
refactor: changing to allow user to pass layout of mosaic subplots ex…

### PR DESCRIPTION
**Pull request by cgodine**
…plicitly as a keyword argument. 

Change will give user more flexibility on how the enhanced skew-t subplots are laid out on the image. 

- [X] Documentation reflects changes
- [X] PEP8 Standards or use of linter

### CODE REVIEW

**Review by zssherman — APPROVED** [review]
@cgodine Thanks for the PR! looks good to me, will see what the tests do.

**Comment by zssherman** [comment]
@cgodine More I thought about it, can we set the default to stay constrained, with the docstring stating that. But still keep the ability for the user to define what they want?

**Comment by cgodine** [comment]
> @cgodine More I thought about it, can we set the default to stay constrained, with the docstring stating that. But still keep the ability for the user to define what they want?

Yeah, I think with the way testing is set up that might be an easier fix.

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
@cgodine Thanks for making the changes, merging!

**Pull request merged**
