### PR TITLE
Random updates

### PR DESCRIPTION
**Pull request by AdamTheisen**
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Review by mgrover1 — COMMENTED** [review]
@AdamTheisen - this will change the API - should we create a v2 tag and pull request to that instead of main?

**Comment by zssherman** [comment]
@mgrover1 @AdamTheisen its a duplicate file and one has a warning, the api won't change on the user's end besides a new warning, and the replacement will also exist.

**Comment by AdamTheisen** [comment]
@mgrover1 what @zssherman said!  :). Shouldn't change the API at the moment.  Figured that we would do some cleanup with V2.

**Comment by mgrover1** [comment]
Okay! Great! I wasn't sure if we wanted to create that separate branch for now - but it sounds like that is a no, so I can go ahead and approve!

**Review by mgrover1 — APPROVED** [review]

**Pull request merged**
