### PR TITLE
Adding SURFRAD Capabilities

### PR DESCRIPTION
**Pull request by AdamTheisen**
- [x] Tests added
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Looks like there are some errors with the PySP2 tests

**Comment by mgrover1** [comment]
@AdamTheisen it appears that there is some 0 shaped array being multiplied within the try/except block...
```python
if np.isfinite(base):
            try:
                height = data_fit.max() - base
                pos = np.argmax(data)
            except ValueError:
                height = np.nan
                pos = np.nan
    
            try:
                start = np.where((data - base) < 50)[0]
>               if start == []:
E               ValueError: operands could not be broadcast together with shapes (14,) (0,)
````

**Comment by zssherman** [comment]
Nothing changed within the pysp2 repo itself, hmm so curious why it's failing now

**Comment by mgrover1** [comment]
> Nothing changed within the pysp2 repo itself, hmm so curious why it's failing now

pysp2 does not currently have a nightly build running/testing with dependencies, so I suspect is has to do with some upstream library cutting a new release

**Comment by mgrover1** [comment]
@zssherman I suspect numpy is the culprit here... https://github.com/numpy/numpy/releases/tag/v1.25.0

**Comment by zssherman** [comment]
@mgrover1 @AdamTheisen Looks like we need a change upstream. So when it checks the start for empty list, check if its a numpy array

**Comment by mgrover1** [comment]
> @mgrover1 @AdamTheisen Looks like we need a change upstream. So when it checks the start for empty list, check if its a numpy array
> 
> ```
> try:
>     start = np.where((data - base) < 50)[0]
>     if start == []:
>         start = np.nan
> ```

Upstream as in pysp2?

**Comment by zssherman** [comment]
@mgrover1 I believe so

**Comment by mgrover1** [comment]
Ahh the good old `method=nearest` argument - good catch @AdamTheisen !

**Comment by AdamTheisen** [comment]
> Ahh the good old `method=nearest` argument - good catch @AdamTheisen !

Found another issue with the plot and the text showing up as expected while looking so it was a good error to help improve the example!

**Review by mgrover1 — COMMENTED** [review]
@AdamTheisen - does their documentation include anything about the `standard_name` for the variables? I think that would be helpful include here if that is the case.

**Comment by AdamTheisen** [comment]
> @AdamTheisen - does their documentation include anything about the `standard_name` for the variables? I think that would be helpful include here if that is the case.

The only documentation they really have is what's in the [README](https://gml.noaa.gov/aftp/data/radiation/surfrad/Boulder_CO/README) file.  They don't have anything about standard_names.

**Comment by mgrover1** [comment]
> > @AdamTheisen - does their documentation include anything about the `standard_name` for the variables? I think that would be helpful include here if that is the case.
> 
> The only documentation they really have is what's in the [README](https://gml.noaa.gov/aftp/data/radiation/surfrad/Boulder_CO/README) file. They don't have anything about standard_names from what I can see.

Gotcha - any chance you could take a look at this table
https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

And see which ones would map? One benefit of using a `cf-standard` name for as many variables as possible is the ability to use tools such as [`cf-xarray`](https://cf-xarray.readthedocs.io/) to generically compare different datastreams using these community standards...

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
Looks good to me, tests are now passing!

**Comment by AdamTheisen** [comment]
Just as a note, I did not get a chance to add in standard names yet. Was hoping to look into that tomorrow

**Comment by mgrover1** [comment]
Sounds good - I think that makes sense for separate PR 😄

**Pull request merged**
