### PR TITLE
FIX: Fix for metpy sounding error.

### PR DESCRIPTION
**Pull request by zssherman**
Error is raised when:
E           metpy.calc.exceptions.InvalidSoundingError:
E                   Pressure does not decrease monotonically in your sounding.
E                   Using scipy.signal.medfilt may fix this.

See if this solves the issue.

### CODE REVIEW

**Comment by zssherman** [comment]
I'm wondering if we need a new sounding test file, I'm not sure how to fix this.

**Comment by AdamTheisen** [comment]
@zssherman  I can take a look.  When I've played around with the sonde data for the PBLHT stuff, there's often a time with the same value as previous so we might just need to resample the data

**Comment by zssherman** [comment]
@AdamTheisen Ah gotcha makes sense, and sounds good.

**Comment by AdamTheisen** [comment]
@zssherman I think i have a fix for this, at least it works on my side of things.

**Comment by zssherman** [comment]
Groovy, yeah looks good to me!

**Comment by AdamTheisen** [comment]
@zssherman we should be good to go here. Will look to @zssherman  to check and merge when approved

**Comment by zssherman** [comment]
Looks good merging thanks @AdamTheisen

**Pull request merged**
