### PR TITLE
Deprecation Warning fix

### PR DESCRIPTION
**Pull request by jhemedin**
Updated the TimeSeriesDisplay.plot() deprecation error when X,Y, and C have the same dimensions in pcolormesh(). 

Added a variable called set_shading that can set the shading parameter to auto and lets matplotlib check if shading should be set to 'flat' or 'nearest' depending on  dimensions.

Default is True but user can set it to false and use kwargs to set the shading parameter.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@jhemedin Thanks for the fix on this!  Looks like just one PEP8 issue

./act/plotting/timeseriesdisplay.py:475:1: W293 blank line contains whitespace

**Review by zssherman — CHANGES_REQUESTED** [review]
Code wise, everything looks good, only thing that needs fixing is the flake8 whitespace that travis flagged.

**Comment by jhemedin** [comment]
removed whitespace, tests are rerunning

**Comment by AdamTheisen** [comment]
@jhemedin that does not seem to have fixed the issue on 475.  Can you take another look?

./act/plotting/timeseriesdisplay.py:475:1: W293 blank line contains whitespace

**Pull request merged**
