### PR TITLE
ICARTT(v2.0) Input module 

### PR DESCRIPTION
**Pull request by jrobrien91**
Module for Reading the International Consortium for Atmospheric
Research on Transport and Transformation (ICARTT) file format standards V2.0

### CODE REVIEW

**Comment by jrobrien91** [comment]
I should note that the example file I included is a full flight of AAF navigation data in the ICARTT format. If we want to cut down on file size, as it is a text file, we can easily remove all but a few data lines.

**Comment by AdamTheisen** [comment]
@jrobrien91 thanks for the PR!  It looks like you have some formatting items to update.  You can always use flake8 to test for these issues on your system as well but here's a list!

./act/io/icartt.py:15:1: E302 expected 2 blank lines, found 1
./act/io/icartt.py:33:51: W291 trailing whitespace
./act/io/icartt.py:70:13: E117 over-indented (comment)
./act/io/icartt.py:71:13: E117 over-indented
./act/io/icartt.py:77:13: E124 closing bracket does not match visual indentation
./act/io/icartt.py:81:5: F841 local variable 'var' is assigned to but never used
./act/io/icartt.py:164:58: E[22](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:23)6 missing whitespace around arithmetic operator
./act/tests/sample_files.py:59:75: W292 no newline at end of file
./act/tests/test_io.py:541:1: E302 expected 2 blank lines, found 1
./act/tests/test_io.py:548:1: W391 blank line at end of file
./examples/plot_icartt.py:17:37: W291 trailing whitespace
./examples/plot_icartt.py:22:45: W291 trailing whitespace
./examples/plot_icartt.py:[23](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:24):74: W291 trailing whitespace
./examples/plot_icartt.py:[24](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:25):61: W291 trailing whitespace
./examples/plot_icartt.py:[26](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:27):38: W[29](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:30)1 trailing whitespace
./examples/plot_icartt.py:[30](https://github.com/ARM-DOE/ACT/runs/8211602967?check_suite_focus=true#step:5:31):36: W291 trailing whitespace

**Comment by zssherman** [comment]
Few things, I would add yourself as an author to the example. remove nonewline in sample_files.py, for pythonic styling change:
```
def read_icartt(
    filename,
    format=icartt.Formats.FFI1001,
    return_None=False,
    **kwargs,
```
to:
```
def read_icartt(filename, format=icartt.Formats.FFI1001,
                        return_None=False, **kwargs,

**Comment by zssherman** [comment]
@jrobrien91 Looks good to me and tests are passing. @AdamTheisen Was there a reason on why we still tests for python 3.6?

**Comment by AdamTheisen** [comment]
@zssherman because that's what is run for the ingests at the adc.

**Comment by AdamTheisen** [comment]
Let me take a look tomorrow before merging. I don't want to have to put through a big fix right away if there is a real issue here

**Comment by AdamTheisen** [comment]
@zssherman this is the error that it's running into.  It looks like it's the ICARTT library.  I'm wondering if we need to make this an optional dependency

```
  Warning: Pip subprocess error:
  ERROR: Package 'icartt' requires a different Python: 3.6.15 not in '<3'
  
  CondaEnvException: Pip failed
  
  Pip subprocess error:
  ERROR: Package 'icartt' requires a different Python: 3.6.15 not in '<3'
```

**Comment by zssherman** [comment]
@AdamTheisen This should work now, 3.7 is just hanging up which has been the case for awhile, but it should run as expected now as optional, and gets installed only for 3.7 and higher.

**Review by mgrover1 — APPROVED** [review]
This looks great! Thanks @jrobrien91 for putting this together

**Pull request merged**
