### PR TITLE
Cb friendly

### PR DESCRIPTION
**Pull request by AdamTheisen**
This would close out #604  but introduces a keyword for the timeseries plot and the qc plot to use colorblind friendly colors.  RGB values were taken from the HomeyerRainbow cmap.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Examples plot changes

ceil_homeyer

image

**Comment by zssherman** [comment]
Looks like just some linting errors, besides that, looks good to me

**Review by zssherman — APPROVED** [review]

**Comment by AdamTheisen** [comment]
Hold off on merging just yet.  I noticed that the 1d timeseries is not the right color.  Need one more fix

**Comment by zssherman** [comment]
Sounds good!

**Comment by AdamTheisen** [comment]
Actually, I think this is good to go.  There's some more complication if we change the colormap for the line plots and it might not play well with many lines.  @zssherman if you're good with this, we can merge in.  Thanks!

**Comment by zssherman** [comment]
Sounds good! merging

**Pull request merged**
