### PR TITLE
CF compliant

### PR DESCRIPTION
**Pull request by kenkehoe**
Making some updates to the netCDF writer to add some additional attributes needed to write a CF compliant data file. This works with issue #252 . I've added attributes for the things I know about, but I would assume I missed one or two. Also, discovered an issue with the QC cleaner that I have updated.

### CODE REVIEW

**Comment by kenkehoe** [comment]
Soooo, I forgot to add testing to this. I'll do that next. But I think something strange is going on with the act/utils/conf/de421.bsp file used with skyfield. We are getting a lot of errors about it not getting closed.

**Comment by AdamTheisen** [comment]
Thanks @kenkehoe I'll take a look at that

**Comment by kenkehoe** [comment]
Looks like something got hung-up with the 3.7 testing and it timed out. I'm going to add some more test coverage and then make another push to run Travis again.

**Comment by AdamTheisen** [comment]
Tests are passing and the code looks good.  Thanks @kenkehoe !

**Pull request merged**
