### PR TITLE
ADD: Adding a script area to ACT to house the ARM Data Surveyor which…

### LINKED ISSUE #626: Add ARM Data Surveyor Command Line Tool
### Description

Migrate functionality from the ARM Data Surveyor
https://code.arm.gov/dq/ADS

to ACT

### PR DESCRIPTION
**Pull request by AdamTheisen**
… is a command-line wrapper around ACT

- [x] Closes #626 
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@zssherman  I added the script and some examples after testing.  I am not sure if we want to pull this scripts area into the documentation or not.  As of now, I was assuming it would be somewhat standalone

**Comment by zssherman** [comment]
@AdamTheisen Yeah to be honest I'm not 100% sure, ill have a think on that, but I'll review this shortly!

**Comment by zssherman** [comment]
@AdamTheisen going to add the setup.py code to have it in scripts from command line

**Comment by zssherman** [comment]
@AdamTheisen Everything looks good to me, @AdamTheisen any more planned changes?

**Review by zssherman — APPROVED** [review]

**Comment by AdamTheisen** [comment]
@zssherman not at the moment! Just wanted to get the initial pr in on this. We can merge

**Pull request merged**
