### PR TITLE
ADD: Adding datetime conversion to datetime_utils.py

### PR DESCRIPTION
**Pull request by jkyrouac**
This adds a conversion to python datetime from numpy datetime64 to the datetime_utils.py module. A test is also added to the test_utils.py module.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
Hi @jkyrouac, it looks like just some formatting/PEP8 issues:

./act/utils/datetime_utils.py:164:22: W503 line break before binary operator
./act/tests/test_utils.py:121:1: W293 blank line contains whitespace
./act/tests/test_utils.py:122:1: W293 blank line contains whitespace
./act/tests/test_utils.py:125:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:126:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:127:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:128:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:131:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:132:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:133:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:134:15: E128 continuation line under-indented for visual indent
./act/tests/test_utils.py:137:56: W291 trailing whitespace

You can update your code, push the commits, and it should be ready to go.

@rcjackson @scollis Since this was from code found online it looks like, is the reference in there appropriate?

**Comment by AdamTheisen** [comment]
One last one
./act/utils/datetime_utils.py:164:22: W503 line break before binary operator

**Comment by jkyrouac** [comment]
@AdamTheisen All fixed!

**Comment by AdamTheisen** [comment]
Just added to the __init__.py file to ensure the documentation shows up

**Pull request merged**
