### PR TITLE
ENH: Bug fix to help with side by side plots on one row (1,2)

### PR DESCRIPTION
**Pull request by AdamTheisen**

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@kenkehoe @ajsockol @cgodine Do you have any side by side plots (multiple columns one row) that this would impact.  I was trying to create a side by side this weekend and it wasn't working as I would expect so made the update.  I.e. I would expect a subplot shape of (1,3) to have subplot indices of (0,0), (0,1), (0,2).  Thanks!

**Comment by kenkehoe** [comment]
I don't think I have created any multi column plots.

**Comment by ajsockol** [comment]
The only one that immediately comes to mind is the stamp_met_precip_comp plot for STAMP. Though, this plot is multiple columns and rows, not multiple columns and one row. If the bug didn't affect plots with multiple columns and rows, then I think the stamp plot should be okay.

**Comment by AdamTheisen** [comment]
@ajsockol This should just affect plots with 1 row and multiple columns so I think that stamp plot should be fine.

**Review by zssherman — APPROVED** [review]
@AdamTheisen Looks good to me

**Pull request merged**
