### PR TITLE
CI: Pinning numpy as binarys between releases are having issues etc.

### LINKED ISSUE #438: Latest Action Runs are Failing
Latest PR and build runs are failing with

```
=================================== FAILURES ===================================
____________________________ test_create_pyart_obj _____________________________

    def test_create_pyart_obj():
        try:
            obj = act.io.mpl.read_sigma_mplv5(act.tests.EXAMPLE_SIGMA_MPLV5)
        except Exception:
            return
    
>       radar = act.utils.create_pyart_obj(obj, range_var='range')

act/tests/test_utils.py:272: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
act/utils/data_utils.py:599: in create_pyart_obj
    import pyart
/usr/share/miniconda3/envs/act_env/lib/python3.8/site-packages/pyart/__init__.py:49: in <module>
    from . import io
/usr/share/miniconda3/envs/act_env/lib/python3.8/site-packages/pyart/io/__init__.py:13: in <module>
    from .sigmet import read_sigmet
/usr/share/miniconda3/envs/act_env/lib/python3.8/site-packages/pyart/io/sigmet.py:14: in <module>
    from ._sigmetfile import SigmetFile, bin4_to_angle, bin2_to_angle
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

pyart/io/_sigmetfile.pyx:1: ValueError
```

### PR DESCRIPTION
**Pull request by zssherman**
Closes #438

### CODE REVIEW

**Comment by zssherman** [comment]
@AdamTheisen @mgrover1 So using the oldest supported numpy in the environment fixed the issue, however wondering if this is the route we want to go? Pinning numpy to the most recent version also solves this issue up into windows python 10 build.

**Comment by zssherman** [comment]
More on it here:
https://github.com/scipy/oldest-supported-numpy

**Comment by mgrover1** [comment]
@zssherman what was the issue with the Windows 10 build?

**Comment by zssherman** [comment]
@mgrover1 Similar to the msv_compiler missing module error that users have reported in Py-ART in the past

**Comment by zssherman** [comment]
```
   Building wheel for arm-pyart (setup.py): finished with status 'done'
  
    Created wheel for arm-pyart: filename=arm_pyart-1.11.8-cp310-cp310-win_amd64.whl size=7998877 sha256=30e90f5346d5662eb4b9f87f22ee2500058699054a4579450895919d2641ad2c
  
    Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\19\a4\4c\9a7e0c0f5faf29c2c0ee32e2d3c9c0e8d325c6b4a3755c3726
  
    Building wheel for numpy (pyproject.toml): started
  
    Building wheel for numpy (pyproject.toml): finished with status 'error'
  
  Successfully built mpl2nc arm-pyart
  
  Failed to build numpy
  
  Warning: Pip subprocess error:
  
  Pip subprocess error:
  Warning:   error: subprocess-exited-with-error
  
    
  
    � Building wheel for numpy (pyproject.toml) did not run successfully.
  
    \u2502 exit code: 1
  
    \u2570\u2500> [319 lines of output]
  
        setup.py:63: RuntimeWarning: NumPy 1.21.0 may not yet support Python 3.10.
  
          warnings.warn(
  
        Running from numpy source directory.
  
        Processing numpy/random\_bounded_integers.pxd.in
  
        Processing numpy/random\bit_generator.pyx
  
        Processing numpy/random\mtrand.pyx
  
        Processing numpy/random\_bounded_integers.pyx.in
  
        Processing numpy/random\_common.pyx
  
        Processing numpy/random\_generator.pyx
  
        Processing numpy/random\_mt19937.pyx
  
        Processing numpy/random\_pcg64.pyx
  
        Processing numpy/random\_philox.pyx
  
        Processing numpy/random\_sfc64.pyx
  
        Cythonizing sources
  
        blas_opt_info:
  
        blas_mkl_info:
  
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  
        customize MSVCCompiler
  
          libraries mkl_rt not found in ['C:\\Miniconda3\\envs\\act_env\\lib', 'C:\\', 'C:\\Miniconda3\\envs\\act_env\\libs']
  
          NOT AVAILABLE
  
        
  
        blis_info:
  
          libraries blis not found in ['C:\\Miniconda3\\envs\\act_env\\lib', 'C:\\', 'C:\\Miniconda3\\envs\\act_env\\libs']
  
          NOT AVAILABLE
         ```

**Comment by mgrover1** [comment]
Ahhh okay thanks @zssherman - I like the idea of pinning the oldest version of numpy, with the caveat that we look into why we can't use the newer versions...

**Comment by zssherman** [comment]
@mgrover1 going to try one more thing. real quick

**Comment by mgrover1** [comment]
@zssherman looks like it's still failing with Windows Python 3.10

**Comment by zssherman** [comment]
@mgrover1 Yeah I was trying to define the numpy build in pyproject, but didn't work sadly.

**Comment by AdamTheisen** [comment]
@zssherman  haven't had much time to look but will try tonight or later this week.  With only one test failing, i want to see what can be done there before making a more significant change like this.  Thoughts?

**Comment by AdamTheisen** [comment]
@zssherman @mgrover1 Okay, I think I have a handle on this one and agree, let's pin this for now but as Max notes, look into the issue more.  If you two agree, we can merge this in, just let me know.

**Comment by mgrover1** [comment]
Yeah @AdamTheisen I think we should merge - some of the setuptools work that @zssherman has been pushing forward on **should** help solve some of these issues...

**Pull request merged**
