### PR TITLE
FIX: Remove verify warning, by setting verify to true.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@zssherman let me test this out a bit.  I know in the past, this caused issues with their API.

**Comment by AdamTheisen** [comment]
@zssherman works fine now but we might want to update the function description as we did note that we were setting that to False

`Note, the requests library
    is indicating a bad handshake with the server so 'verify' is currently
    set to False which is unsecure`

Wondering if we need an issue to add a citation as well... Thoughts?
`USDA National Agricultural Statistics Service Cropland Data Layer. {YEAR}. Published crop-specific data layer [Online]. Available at https://nassgeodata.gmu.edu/CropScape/ (accessed {DATE}; verified {DATE}). USDA-NASS, Washington, DC.`

**Comment by zssherman** [comment]
Oh yep! I missed that note, I can remove it, but agreed I think a citation would be good

**Comment by zssherman** [comment]
@AdamTheisen I updated the PR to remove the note and added the reference, let me know if it looks good!

**Review by AdamTheisen — APPROVED** [review]

**Comment by AdamTheisen** [comment]
@zssherman I think this is good to go!  Thanks!

**Pull request merged**
