### PR TITLE
FIX: Update versioneer.py for python 3.12 support.

### PR DESCRIPTION
**Pull request by zssherman**

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]

**Comment by mgrover1** [comment]
Thanks for the quick fix here @zssherman

**Comment by zssherman** [comment]
Geoplot test is giving different results for the array each time it runs for ubuntu....

**Comment by mgrover1** [comment]
@zssherman - the default figsize changes every time. The best way forward is to manually set the figsize, I added a fix here with an update to the image to validate.

**Comment by mgrover1** [comment]
@zssherman - tests are good to go! The base image just needed to update I believe

**Pull request merged**
