### PR TITLE
ENH: Rename the csv module to prevent errors

### LINKED ISSUE #787: Rename CSV submodule
* ACT version: 2.0
* Python version: All
* Operating System: All

### Description

We should consider renaming the `act.io.csv` submodule in ACT. It will lead to import issues with pandas, as it is not recommended to have modules titled `csv`

[see the thread here](https://stackoverflow.com/questions/60912657/python-pandas-cannot-import-quote-minimal)

We can still keep the same API - `read_csv`, but we should rename to something like "text" or "tabular". Thoughts?

### What I Did

Upon submitting a PR, the following error appeared:

```python
ImportError: cannot import name 'QUOTE_NONNUMERIC' from partially initialized module 'csv' (most likely due to a circular import) (/Users/jrobrien/dev/ACT/act/io/csv.py)
```

### PR DESCRIPTION
**Pull request by mgrover1**
Rename the csv module to text
- [x] Closes #787 
- [x] Tests added
- [x] Documentation reflects changes
- [x] PEP8 Standards or use of linter
- [x] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by zssherman** [comment]
@mgrover1 Looks good to me, failing test seems to be an import error still, the doc build fail is strange as we don't pin sphinx, maybe because we pip install it in the enviromnet_docs.yml and its pip installing an earlier version?

**Comment by zssherman** [comment]
@mgrover1 Looks like pysp2 doc is failing due to sphinx as well, wonder if sphinx did an update...

**Comment by mgrover1** [comment]
Yes, it is happening across the Pythia sphere as well

**Comment by zssherman** [comment]
@mgrover1 Ah makes sense....

**Comment by mgrover1** [comment]
see the discussion here https://github.com/ProjectPythia/cookbook-template/issues/154

**Comment by zssherman** [comment]
@mgrover1 found the problem think its fixed.

**Comment by zssherman** [comment]
Surprised that didn't fix the issue...

**Comment by mgrover1** [comment]
@zssherman - the `act.io.noaapsl` submodule's import was inconsistent - I pushed a fix

**Comment by zssherman** [comment]
@mgrover1 I added in the noaa psl change to test it out, but the init was missing text instead of csv for the top module. Thought that would have fixed the issue.

**Comment by mgrover1** [comment]
It would help if the submodule were actually added... that last push should resolve the issues 👍

**Comment by mgrover1** [comment]
@rcjackson - this is a solid state now - do you have the PR ready to merge or do a release of PySP2

**Review by zssherman — APPROVED** [review]
Changes look good, approving until the release of pysp2.

**Comment by rcjackson** [comment]
New release of PySP2 is out on PyPI, so once that gets through these unit tests should succeed. PySP2's are succeeding on my machine with @mgrover1 's fork installed though currently failing online because this PR and release is not done.

**Comment by AdamTheisen** [comment]
@zssherman would you want to get a new release done today?

**Comment by zssherman** [comment]
@AdamTheisen Yeah, I can do that!

**Comment by zssherman** [comment]
@AdamTheisen An issue with the PySP2 release, going to get that fix, then can do the ACT release

**Review by AdamTheisen — APPROVED** [review]

**Comment by mgrover1** [comment]
Can I hit merge?

**Comment by zssherman** [comment]
@mgrover1 Yep was waiting on pysp2 to catch up!

**Pull request merged**
