### PR TITLE
Updated to set data as Dask array back in Dataset if data is originally stored as Dask array

### PR DESCRIPTION
**Pull request by kenkehoe**
Noticed this method was not storing the data back in the Dataset in the same format as was retrieved. This will check if data is set as Dask array and set data to same data type. Also, added some more tests.

### CODE REVIEW

**Comment by kenkehoe** [comment]
Also, once this PR is merged can we make a release to provide access to some recent updates. @AdamTheisen

**Comment by AdamTheisen** [comment]
Sounds good @kenkehoe requesting a review from @zssherman and then maybe after he can do a new release and work with @mgrover1 on getting familiar with our process

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
Sounds good @AdamTheisen !

**Review by mgrover1 — APPROVED** [review]
Looks great!

**Pull request merged**
