### PR TITLE
DOC: Fix of typos and mispellings as well as PEP8 changes.

### PR DESCRIPTION
**Pull request by zssherman**
Particularly carbon dioxide was suppose to be ozone for gml_ozone and meteorological was spelled wrong.

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]
Great! Thanks @zssherman

**Comment by mgrover1** [comment]
Looks like one small flake8 issue

**Comment by zssherman** [comment]
Cool! Thanks for catching that and changing it

**Comment by mgrover1** [comment]
Once the tests pass we can merge

**Pull request merged**
