### PR TITLE
Pint update to stop warning

### PR DESCRIPTION
**Pull request by kenkehoe**
- [X ] Documentation reflects changes
- [ X] PEP8 Standards or use of linter
- [ X] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

The Pint library is warning of redefining units. This update correctly adds the desired units and stops redefining units. Also commented out some return statements in plotting testing to stop warnings of future errors.

### CODE REVIEW

**Review by zssherman — APPROVED** [review]

**Comment by zssherman** [comment]
Closing and reopening to run tests as github was down

**Review by AdamTheisen — APPROVED** [review]

**Comment by AdamTheisen** [comment]
Looks good once the final test passes

**Comment by kenkehoe** [comment]
@AdamTheisen  what are the chances of getting a release with this update? We are getting a warning and my attempts to stop sending alerts to us about the warning are not working. If we make this update I can stop those warnings sending us emails.

**Comment by zssherman** [comment]
@kenkehoe I can get one out today!

**Comment by zssherman** [comment]
@kenkehoe The github and pypi release is out, just waiting on conda-forge to pick up the pypi release

**Pull request merged**
