### PR TITLE
Added keyword to apply clean.cleanup() method instead of requiring the method call after reading data.

### PR DESCRIPTION
**Pull request by kenkehoe**
Also fixed an issue with using pathlib.Path().

### CODE REVIEW

**Review by mgrover1 — COMMENTED** [review]
@kenkehoe what is the reason for using `PosixPath` here instead of the more generic `Path`?

**Review by mgrover1 — APPROVED** [review]
Thanks @kenkehoe for putting this together!

**Comment by mgrover1** [comment]
@kenkehoe is this good to merge?

**Comment by kenkehoe** [comment]
Yes I believe so @mgrover1

**Pull request merged**
