### PR TITLE
Add pydata theme, similar to PyART

### PR DESCRIPTION
**Pull request by mgrover1**
This adds a new theme, and fixes some of the examples that aren't running. I also found a bug in the sounding calculation example (wrong variable name for relative humidity)

Here's a screenshot of the new look
Screen Shot 2022-04-01 at 2 41 54 PM

### CODE REVIEW

**Review by zssherman — APPROVED** [review]
Looks good to me!

**Comment by mgrover1** [comment]
@zssherman good to merge? 👀

**Comment by mgrover1** [comment]
Wait - one more thing

**Comment by AdamTheisen** [comment]
Will wait for @mgrover1 to verify before merging anything in

**Comment by mgrover1** [comment]
Merged with the most recent updates - should be good to go after this.

**Pull request merged**
