### PR TITLE
Comparison Display 

### PR DESCRIPTION
**Pull request by jrobrien91**
New Display object to compare two datastreams through the use of scatter and violin plots.
- Scatter plots allow for plotting of non-time variable along the x-axis
    - complement to 2D Histogram plot within HistogramDisplay
- Violin plots allow a view of the data distribution and Interquartile range

- [X] Closes/First Cut at #459 
- [X] Tests added
- [X] Documentation reflects changes
- [X] PEP8 Standards or use of linter
- [X] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming

### CODE REVIEW

**Comment by zssherman** [comment]
@jrobrien91 I'll take a look tomorrow

**Comment by AdamTheisen** [comment]
In meetings all day but can look and test out tomorrow

**Comment by AdamTheisen** [comment]
@jrobrien91 this is looking good!  I want to get feedback from @mgrover1 and @zssherman but I'm wondering if ComparisonDisplay is the best class name for these.  I.e. would ScatterDisplay be better for the scatter plot and something like DistributionDisplay for the violin or something like that?  

Which leads me to wondering if we need to rename the HistogramDisplay to DistributionDisplay?  Thoughts?

**Comment by jrobrien91** [comment]
@AdamTheisen but I agree, `ComparisonDisplay` was always an awful name and another name more helpful would be appreciated

**Comment by mgrover1** [comment]
I like the idea of consolidating this into `DistributionDisplay`

**Comment by zssherman** [comment]
@jrobrien91 @AdamTheisen @mgrover1 I second a distribution display with  the underlying functions between this all within the module.

**Comment by zssherman** [comment]
If were all in agreement, I say make the changes and I can review it once its done.

**Comment by AdamTheisen** [comment]
@zssherman @mgrover1 do we need to keep the HistogramDisplay option around with a deprecation warning for a bit or do you think we can go forward with the change and do a minor release?

**Comment by mgrover1** [comment]
Let's put in a deprecation warning and remove in the next major release!

**Comment by AdamTheisen** [comment]
Sounds good @mgrover1 !

One last comment on the scatter plot.  It might be very helpful to be able to pass in a dsname for the x and y variables separately.  For example, I might want to compare the temperature from the MET and MAWS systems.  Is that doable?  Happy to help with these other updates as well.

**Review by zssherman — APPROVED** [review]
Everything looks good to me @jrobrien91 @AdamTheisen. I have no comments, I think the depreciation warning is good as well!

**Review by mgrover1 — APPROVED** [review]
Looks good to merge! Thank you for the changes @jrobrien91 @AdamTheisen

**Pull request merged**
