### PR TITLE
DOC: Overhaul of index page.

### PR DESCRIPTION
**Pull request by zssherman**
Adding example images, hid the api doc tree and adding basic introduction information. Also added links to conda and github downloads.

### CODE REVIEW

**Comment by zssherman** [comment]
Seems failure is not related, but a connection error to croptype module, maybe the website is down at the moment.

**Comment by rcjackson** [comment]
Do you by chance have a screenshot of the index page? I'd just like to take a look at it before finalizing approval.

**Comment by zssherman** [comment]
Yeah no problem, just having an issue with an error:
TypeError: open_dataset() got an unexpected keyword argument 'combine'
for one of the examples

**Comment by AdamTheisen** [comment]
@zssherman which example?  I'm wondering if it has to do with the updates Ken made to the reader to ensure it read the time correctly.  Might not need that keyword anymore

**Comment by zssherman** [comment]
Yep, I just had to remove the generated folder and examples folder and regenerate them with the updated ACT, we are good now

**Comment by zssherman** [comment]
Screenshot from 2020-02-07 10-41-08
Screenshot from 2020-02-07 10-41-15
Screenshot from 2020-02-07 10-41-20

**Comment by zssherman** [comment]
@rcjackson @AdamTheisen This is what the new page looks like

**Comment by zssherman** [comment]
More I think about it, the second plot might be overkill, your thoughts?

**Comment by AdamTheisen** [comment]
@zssherman It might be good to remove it to clear up that space a bit

**Comment by rcjackson** [comment]
I agree, I think the front page should only have one plot. After you remove that, we can approve.

**Comment by AdamTheisen** [comment]
@rcjackson are you able to restart the build for these PR's?  I don't seem to have access to.

**Comment by zssherman** [comment]
Removed the second plot CI should be restarting

**Comment by rcjackson** [comment]
I just restarted the build on my PR. Make sure you are logged in when you’re in Travis CI, that was the issue I had that wasn’t letting me rebuild.

**Pull request merged**
