### PR TITLE
ADD: Ability to load DOD from file for create_obj_from_arm_dod

### PR DESCRIPTION
**Pull request by rcjackson**
This resolves issue #584 where the user can now specify a file to load the DOD from when creating an ACT object from a DOD. The DOD filename is specified in the proc string, and if the local_file flag is set to True then ACT will load the DOD from the file location instead of from PCM.

### CODE REVIEW

**Comment by zssherman** [comment]
Thanks @rcjackson for putting this together! Looks like it's failing to pep8 stuff

**Review by zssherman — APPROVED** [review]
Approved, is the drop due to this PR?

**Comment by zssherman** [comment]
@AdamTheisen is this what happened to that other PR? Its showing a drop in get_airnow

**Comment by AdamTheisen** [comment]
@zssherman that is strange.  It shouldn't fluctuate that much from PR to PR as it's been consistently around 1.7 now.  I'm rerunning again and will see what happens.  Coveralls is not really showing any differences besides the known ones.

**Comment by zssherman** [comment]
Yeah, the code itself is sound, once the tests pass we can merge and see if the coverage resolves

**Comment by AdamTheisen** [comment]
@zssherman  I would say that once these tests all pass we force the merge and see what happens on production.  I can always update the threshold again for coveralls

**Pull request merged**
