### PR TITLE
FIX: Figure size wasn't being set correctly in Xsectiondisplay

### PR DESCRIPTION
**Pull request by zssherman**
subplot was being overwritten and figure size would not change the plot when calling figsize in XsectionDisplay. This has been fixed as well as the example.

### CODE REVIEW

**Comment by zssherman** [comment]
Trying to figure out how to replace the baselines...

**Comment by AdamTheisen** [comment]
@zssherman if you run this, it will recreate all the baseline images. Then you can just check the cross-section plots and commit them.  

```
pytest --mpl-generate-path=baseline
```

**Comment by zssherman** [comment]
@AdamTheisen Ah gotcha, thanks! I will do that!

**Review by mgrover1 — APPROVED** [review]
Good move setting the figsize

**Pull request merged**
